__title__ = "interva"
__description__ = "Python implementation of the InterVA Algorithm."
__url__ = "https://github.com/verbal-autopsy-software/interva"
__version__ = "0.0.7"
__author__ = "Sherry Zhao & Jason Thomas"
__author_email__ = "zhao.3248@buckeyemail.osu.edu"
__license__ = "GPLv3"
